spring.application.name=worktrack
spring.datasource.url=jdbc:mysql://localhost:3306/worktrack
spring.datasource.username=root
spring.datasource.password=StJude@07

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.format_sql=true

